const data = [
  {
    id: 1,
    title: "URL shortner",
    desc: "This project is based off this challenge. Wrangled with styling HighCharts and learned the use of Promises. Data is from the Tradier API. Search autocomplete relies on the lookup endpoint and sometimes runs slow. Please be patient!",
    stack: [
      "html",
      "css",
      "javascript",
      "es6",
      "react js",
      "react router",
      "axios",
      "node js",
      "express js",
      "netlify",
      "serverless",
      "mysql",
    ],
    demo: "https://urlshortner.abidhassan.dev/",
    source: "https://github.com/ghulamabidhassan/urlshortner",
    image: "./images/vector.jpg",
  },
  {
    id: 2,
    title: "dev jobs search",
    desc: "This project is based off this challenge. Wrangled with styling HighCharts and learned the use of Promises. Data is from the Tradier API. Search autocomplete relies on the lookup endpoint and sometimes runs slow. Please be patient!",
    stack: [
      "html",
      "css",
      "javascript",
      "es6",
      "react js",
      "react router",
      "axios",
      "node js",
      "express js",
      "netlify",
      "serverless",
    ],
    demo: "https://jobs.abidhassan.dev/",
    source:
      "https://github.com/ghulamabidhassan/API-Projects/tree/master/Devjobs%20Web%20App",
    image: "./images/vector.jpg",
  },
  {
    id: 3,
    title: "github users",
    desc: "This project is based off this challenge. Wrangled with styling HighCharts and learned the use of Promises. Data is from the Tradier API. Search autocomplete relies on the lookup endpoint and sometimes runs slow. Please be patient!",
    stack: [
      "html",
      "css",
      "javascript",
      "es6",
      "reactjs",
      "axios",
      "moment js",
      "github api",
    ],
    demo: "https://githubusers.abidhassan.dev/",
    source:
      "https://github.com/ghulamabidhassan/API-Projects/tree/master/Github%20Users%20API",
    image: "./images/vector.jpg",
  },
  {
    id: 4,
    title: "movie database",
    desc: "This project is based off this challenge. Wrangled with styling HighCharts and learned the use of Promises. Data is from the Tradier API. Search autocomplete relies on the lookup endpoint and sometimes runs slow. Please be patient!",
    stack: [
      "html",
      "css",
      "javascript",
      "es6",
      "reactjs",
      "react router",
      "axios",
      "omdb api",
    ],
    demo: "https://moviedb.abidhassan.dev/",
    source:
      "https://github.com/ghulamabidhassan/API-Projects/tree/master/Movies-Database",
    image: "./images/vector.jpg",
  },
  {
    id: 5,
    title: "IP address tracker",
    desc: "This project is based off this challenge. Wrangled with styling HighCharts and learned the use of Promises. Data is from the Tradier API. Search autocomplete relies on the lookup endpoint and sometimes runs slow. Please be patient!",
    stack: ["html", "css", "javascript", "es6", "reactjs", "leaflet maps"],
    demo: "https://iptracker.abidhassan.dev/",
    source:
      "https://github.com/ghulamabidhassan/frontend-mentor-react-projects/tree/master/20-Ip-address-tracker",
    image: "./images/vector.jpg",
  },
  {
    id: 6,
    title: "To-do list",
    desc: "This project is based off this challenge. Wrangled with styling HighCharts and learned the use of Promises. Data is from the Tradier API. Search autocomplete relies on the lookup endpoint and sometimes runs slow. Please be patient!",
    stack: ["html", "css", "javascript", "es6", "react js"],
    demo: "https://todoapp.abidhassan.dev/",
    source:
      "https://github.com/ghulamabidhassan/frontend-mentor-react-projects/tree/master/16-Todo-App",
    image: "./images/vector.jpg",
  },
  {
    id: 7,
    title: "jobs list with filtering",
    desc: "This project is based off this challenge. Wrangled with styling HighCharts and learned the use of Promises. Data is from the Tradier API. Search autocomplete relies on the lookup endpoint and sometimes runs slow. Please be patient!",
    stack: ["html", "css", "javascript", "es6", "reactjs"],
    demo: "https://jobfilter.abidhassan.dev/",
    source:
      "https://github.com/ghulamabidhassan/frontend-mentor-react-projects/tree/master/15-Jobs-listings-with-filtering",
    image: "./images/vector.jpg",
  },
  {
    id: 8,
    title: "social media dashboard",
    desc: "This project is based off this challenge. Wrangled with styling HighCharts and learned the use of Promises. Data is from the Tradier API. Search autocomplete relies on the lookup endpoint and sometimes runs slow. Please be patient!",
    stack: ["html", "css", "javascript", "es6", "reactjs"],
    demo: "https://socialdashboard.abidhassan.dev/",
    source:
      "https://github.com/ghulamabidhassan/frontend-mentor-react-projects/tree/master/9-Social-media-dashboard",
    image: "./images/vector.jpg",
  },
  {
    id: 9,
    title: "rock paper scissors game",
    desc: "This project is based off this challenge. Wrangled with styling HighCharts and learned the use of Promises. Data is from the Tradier API. Search autocomplete relies on the lookup endpoint and sometimes runs slow. Please be patient!",
    stack: ["html", "css", "javascript", "es6", "reactjs"],
    demo: "https://rpsgame.abidhassan.dev/",
    source:
      "https://github.com/ghulamabidhassan/frontend-mentor-react-projects/tree/master/21-Rock-paper-scissors-game",
    image: "./images/vector.jpg",
  },
  {
    id: 10,
    title: "calculator",
    desc: "This project is based off this challenge. Wrangled with styling HighCharts and learned the use of Promises. Data is from the Tradier API. Search autocomplete relies on the lookup endpoint and sometimes runs slow. Please be patient!",
    stack: ["html", "css", "javascript", "es6", "reactjs"],
    demo: "https://calci.abidhassan.dev/",
    source:
      "https://github.com/ghulamabidhassan/frontend-mentor-react-projects/tree/master/14-Calculator-app",
    image: "./images/vector.jpg",
  },

  {
    id: 11,
    title: "loopstudios landing page",
    desc: "This project is based off this challenge. Wrangled with styling HighCharts and learned the use of Promises. Data is from the Tradier API. Search autocomplete relies on the lookup endpoint and sometimes runs slow. Please be patient!",
    stack: ["html", "css", "javascript", "es6", "reactjs"],
    demo: "https://loopstudio.abidhassan.dev/",
    source:
      "https://github.com/ghulamabidhassan/frontend-mentor-react-projects/tree/master/5-Loopstudios-landing-page",
    image: "./images/vector.jpg",
  },
];

export default data;
